apiVersion: v1
kind: Service
metadata:
  name: agroconecta-backend-service
  namespace: agroconecta
  labels:
    app: agroconecta-backend
spec:
  type: LoadBalancer
  selector:
    app: agroconecta-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
